/**
 * NetraScan Retinal Lesion & Biomarker Localization Formatter
 * Standardizes real clinical lesion findings (MA, HE, EX, SE) returned by the backend AI engine
 * with exact normalized bounding boxes [x, y, w, h], center coordinates [cx, cy],
 * and pointing arrow callouts for explainable clinical reporting and workstation visualization.
 */

export const LESION_TYPES = {
  MA: {
    code: "MA",
    name: "Microaneurysm",
    plural: "Microaneurysms",
    description: "Focal capillary dilations and punctate red microvascular lesions",
    color: "#EF4444",
    bg: "rgba(239, 68, 68, 0.22)",
    border: "#DC2626",
    badgeBg: "#7F1D1D",
  },
  HE: {
    code: "HE",
    name: "Intraretinal Hemorrhage",
    plural: "Hemorrhages",
    description: "Deep intraretinal dot, blot, and flame-shaped microvascular bleeds",
    color: "#F97316",
    bg: "rgba(249, 115, 22, 0.22)",
    border: "#EA580C",
    badgeBg: "#7C2D12",
  },
  EX: {
    code: "EX",
    name: "Hard Exudate",
    plural: "Hard Exudates",
    description: "Lipid, lipoprotein, and protein precipitates with discrete margins",
    color: "#EAB308",
    bg: "rgba(234, 179, 8, 0.26)",
    border: "#CA8A04",
    badgeBg: "#713F12",
  },
  SE: {
    code: "SE",
    name: "Soft Exudate (Cotton Wool Spot)",
    plural: "Soft Exudates",
    description: "Localized microinfarctions of the retinal nerve fiber layer (axoplasmic debris)",
    color: "#0284C7",
    bg: "rgba(2, 132, 199, 0.24)",
    border: "#0369A1",
    badgeBg: "#0C4A6E",
  },
};

/**
 * Extracts and normalizes genuine clinical lesion findings from the backend AI model response.
 * Strictly preserves the real counts and findings generated by the backend model.
 */
export function normalizeLesions(input) {
  if (!input) {
    return {
      total_count: 0,
      by_type: { MA: 0, HE: 0, EX: 0, SE: 0 },
      findings: [],
    };
  }

  // Handle case where input is already the lesions object or container
  let rawLesions = null;
  if (input.by_type || (input.findings && !input.lesions)) {
    rawLesions = input;
  } else if (input.lesions) {
    rawLesions = input.lesions;
  } else if (input.ai_evidence?.lesions) {
    rawLesions = input.ai_evidence.lesions;
  } else {
    return {
      total_count: 0,
      by_type: { MA: 0, HE: 0, EX: 0, SE: 0 },
      findings: [],
    };
  }

  const findings = Array.isArray(rawLesions.findings) ? rawLesions.findings : [];
  const byType = rawLesions.by_type || { MA: 0, HE: 0, EX: 0, SE: 0 };
  const totalCount = rawLesions.total_count ?? (
    (byType.MA || 0) + (byType.HE || 0) + (byType.EX || 0) + (byType.SE || 0)
  );

  return {
    total_count: totalCount,
    by_type: {
      MA: Number(byType.MA) || 0,
      HE: Number(byType.HE) || 0,
      EX: Number(byType.EX) || 0,
      SE: Number(byType.SE) || 0,
    },
    findings,
  };
}

/** Backwards-compatible alias */
export const getOrSynthesizeLesions = normalizeLesions;
