/**
 * NetraScan Retinal Lesion & Biomarker Localization Formatter
 * Standardizes real clinical lesion findings (MA, HE, EX, SE) returned by the backend AI engine
 * with exact normalized bounding boxes [x, y, w, h], center coordinates [cx, cy],
 * and pointing arrow callouts for explainable clinical reporting and workstation visualization.
 */

export const LESION_TYPES = {
  MA: {
    code: "MA",
    name: "Microaneurysm",
    plural: "Microaneurysms",
    description: "Focal capillary dilations and punctate red microvascular lesions",
    color: "#EF4444",
    bg: "rgba(239, 68, 68, 0.22)",
    border: "#DC2626",
    badgeBg: "#7F1D1D",
  },
  HE: {
    code: "HE",
    name: "Intraretinal Hemorrhage",
    plural: "Hemorrhages",
    description: "Deep intraretinal dot, blot, and flame-shaped microvascular bleeds",
    color: "#F97316",
    bg: "rgba(249, 115, 22, 0.22)",
    border: "#EA580C",
    badgeBg: "#7C2D12",
  },
  EX: {
    code: "EX",
    name: "Hard Exudate",
    plural: "Hard Exudates",
    description: "Lipid, lipoprotein, and protein precipitates with discrete margins",
    color: "#EAB308",
    bg: "rgba(234, 179, 8, 0.26)",
    border: "#CA8A04",
    badgeBg: "#713F12",
  },
  SE: {
    code: "SE",
    name: "Soft Exudate (Cotton Wool Spot)",
    plural: "Soft Exudates",
    description: "Localized microinfarctions of the retinal nerve fiber layer (axoplasmic debris)",
    color: "#0284C7",
    bg: "rgba(2, 132, 199, 0.24)",
    border: "#0369A1",
    badgeBg: "#0C4A6E",
  },
};

/**
 * Extracts and normalizes genuine clinical lesion findings from the backend AI model response.
 * Strictly preserves the real counts and findings generated by the backend model.
 */
export function normalizeLesions(input) {
  if (!input) {
    return {
      total_count: 0,
      by_type: { MA: 0, HE: 0, EX: 0, SE: 0 },
      findings: [],
    };
  }

  // Parse if input itself is a JSON string
  if (typeof input === "string") {
    try {
      input = JSON.parse(input);
    } catch {
      return {
        total_count: 0,
        by_type: { MA: 0, HE: 0, EX: 0, SE: 0 },
        findings: [],
      };
    }
  }

  let rawLesions = null;

  // 1. Direct lesions object (contains by_type or findings or total_count)
  if (input.by_type || (Array.isArray(input.findings) && !input.lesions)) {
    rawLesions = input;
  }
  // 2. Container object with .lesions property
  else if (input.lesions) {
    let l = input.lesions;
    if (typeof l === "string") {
      try { l = JSON.parse(l); } catch { l = null; }
    }
    if (l && typeof l === "object") {
      rawLesions = l;
    }
  }
  // 3. Container object with .ai_evidence property
  else if (input.ai_evidence) {
    let ev = input.ai_evidence;
    if (typeof ev === "string") {
      try { ev = JSON.parse(ev); } catch { ev = null; }
    }
    if (ev && typeof ev === "object" && ev.lesions) {
      rawLesions = typeof ev.lesions === "string" ? JSON.parse(ev.lesions) : ev.lesions;
    }
  }
  // 4. Container object with .evidence property (if evidence was serialized with lesions)
  else if (input.evidence && typeof input.evidence === "object" && input.evidence.lesions) {
    rawLesions = typeof input.evidence.lesions === "string" ? JSON.parse(input.evidence.lesions) : input.evidence.lesions;
  }

  if (!rawLesions || typeof rawLesions !== "object") {
    return {
      total_count: 0,
      by_type: { MA: 0, HE: 0, EX: 0, SE: 0 },
      findings: [],
    };
  }

  const findings = Array.isArray(rawLesions.findings) ? rawLesions.findings : [];
  const rawByType = rawLesions.by_type || {};

  const byType = {
    MA: Number(rawByType.MA) || 0,
    HE: Number(rawByType.HE) || 0,
    EX: Number(rawByType.EX) || 0,
    SE: Number(rawByType.SE) || 0,
  };

  // If byType is all 0s but findings exist, count from findings
  if (byType.MA === 0 && byType.HE === 0 && byType.EX === 0 && byType.SE === 0 && findings.length > 0) {
    findings.forEach((f) => {
      const type = f.type || "EX";
      if (byType[type] !== undefined) {
        byType[type] = (byType[type] || 0) + 1;
      }
    });
  }

  const sumByType = byType.MA + byType.HE + byType.EX + byType.SE;
  const totalCount = rawLesions.total_count !== undefined && rawLesions.total_count !== null
    ? Number(rawLesions.total_count)
    : Math.max(sumByType, findings.length);

  return {
    total_count: totalCount,
    by_type: byType,
    findings,
  };
}

/** Backwards-compatible alias */
export const getOrSynthesizeLesions = normalizeLesions;
