import {
  PatientInfo,
  ScreeningSession,
  ClinicalReport,
  ModelMetrics,
  SystemHealthData,
  AnalysisSuccessResponse,
} from '../types';

// Sample Base64 synthetic retina image and Grad-CAM for immediate preview
export const DEMO_FUNDUS_SVG = `data:image/svg+xml;utf8,<svg xmlns="http://www.w3.org/2000/svg" width="400" height="400" viewBox="0 0 400 400"><defs><radialGradient id="fundusBg" cx="50%" cy="50%" r="50%"><stop offset="0%" stop-color="%23d94812"/><stop offset="60%" stop-color="%239a2c0a"/><stop offset="90%" stop-color="%235a1204"/><stop offset="100%" stop-color="%231a0501"/></radialGradient><radialGradient id="opticDisc" cx="50%" cy="50%" r="50%"><stop offset="0%" stop-color="%23ffeb99"/><stop offset="70%" stop-color="%23f5b041"/><stop offset="100%" stop-color="%23d68910"/></radialGradient><filter id="blur"><feGaussianBlur stdDeviation="3"/></filter></defs><rect width="400" height="400" fill="%2305070a"/><circle cx="200" cy="200" r="185" fill="url(%23fundusBg)"/><circle cx="120" cy="200" r="28" fill="url(%23opticDisc)"/><circle cx="250" cy="205" r="12" fill="%236e1a06" filter="url(%23blur)" opacity="0.8"/><path d="M120 200 Q 150 140 220 110 T 320 90" stroke="%23580e03" stroke-width="6" fill="none" stroke-linecap="round"/><path d="M120 200 Q 150 260 230 290 T 330 310" stroke="%23580e03" stroke-width="6.5" fill="none" stroke-linecap="round"/><path d="M120 200 Q 80 140 40 100" stroke="%23781506" stroke-width="4.5" fill="none" stroke-linecap="round"/><path d="M120 200 Q 80 260 40 300" stroke="%23781506" stroke-width="4.5" fill="none" stroke-linecap="round"/><circle cx="240" cy="180" r="3.5" fill="%23400502"/><circle cx="260" cy="225" r="4.2" fill="%23400502"/><circle cx="215" cy="235" r="3" fill="%23400502"/><circle cx="280" cy="165" r="5" fill="%23fff2a8" opacity="0.85"/><circle cx="295" cy="180" r="4" fill="%23fff2a8" opacity="0.85"/><circle cx="270" cy="245" r="7" fill="%23e84118" opacity="0.75" filter="url(%23blur)"/><circle cx="225" cy="155" r="8" fill="%23e84118" opacity="0.7" filter="url(%23blur)"/></svg>`;

export const DEMO_HEATMAP_SVG = `data:image/svg+xml;utf8,<svg xmlns="http://www.w3.org/2000/svg" width="400" height="400" viewBox="0 0 400 400"><defs><radialGradient id="hotspot1" cx="50%" cy="50%" r="50%"><stop offset="0%" stop-color="%23ff0000" stop-opacity="0.85"/><stop offset="40%" stop-color="%23ffaa00" stop-opacity="0.65"/><stop offset="70%" stop-color="%2300ff00" stop-opacity="0.35"/><stop offset="100%" stop-color="%230000ff" stop-opacity="0"/></radialGradient><radialGradient id="hotspot2" cx="50%" cy="50%" r="50%"><stop offset="0%" stop-color="%23ff0055" stop-opacity="0.8"/><stop offset="50%" stop-color="%23ffcc00" stop-opacity="0.5"/><stop offset="100%" stop-color="%2300ffff" stop-opacity="0"/></radialGradient><radialGradient id="fundusBg" cx="50%" cy="50%" r="50%"><stop offset="0%" stop-color="%23d94812"/><stop offset="60%" stop-color="%239a2c0a"/><stop offset="90%" stop-color="%235a1204"/><stop offset="100%" stop-color="%231a0501"/></radialGradient></defs><rect width="400" height="400" fill="%2305070a"/><circle cx="200" cy="200" r="185" fill="url(%23fundusBg)"/><circle cx="260" cy="200" r="75" fill="url(%23hotspot1)"/><circle cx="230" cy="160" r="55" fill="url(%23hotspot2)"/><circle cx="280" cy="240" r="45" fill="url(%23hotspot2)"/></svg>`;

export const SAMPLE_PRESET_SCANS = [
  {
    id: 'sample-moderate-npdr',
    title: 'Preset: Moderate NPDR (Grade 2)',
    description: 'Patient with microaneurysms, blot hemorrhages & hard exudates in temporal quadrant',
    stage: 2,
    stageName: 'Moderate Non-Proliferative Diabetic Retinopathy',
    confidence: 0.914,
    referable: true,
    file_name: 'fundus_moderate_npdr_02.jpg',
    patient: {
      patient_id: 'PAT-48291',
      name: 'Ramesh Patel',
      age: 58,
      gender: 'Male' as const,
      examined_eye: 'OD - Right Eye' as const,
      diabetes_type: 'Type 2',
      duration_years: 11,
      clinician_notes: 'Referred from PHC for routine 6-month diabetic retinopathy evaluation.',
    },
  },
  {
    id: 'sample-normal',
    title: 'Preset: Healthy Retina (Grade 0)',
    description: 'Clear foveal avascular zone, distinct optic disc, zero microvascular lesions',
    stage: 0,
    stageName: 'No Diabetic Retinopathy',
    confidence: 0.985,
    referable: false,
    file_name: 'fundus_healthy_normal_01.jpg',
    patient: {
      patient_id: 'PAT-10928',
      name: 'Priya Sharma',
      age: 42,
      gender: 'Female' as const,
      examined_eye: 'OS - Left Eye' as const,
      diabetes_type: 'Type 2',
      duration_years: 3,
      clinician_notes: 'Initial baseline screening post-HbA1c diagnosis (6.8%).',
    },
  },
  {
    id: 'sample-severe-npdr',
    title: 'Preset: Severe NPDR (Grade 3)',
    description: 'Extensive intraretinal hemorrhages in 4 quadrants (4-2-1 rule) with IRMA',
    stage: 3,
    stageName: 'Severe Non-Proliferative Diabetic Retinopathy',
    confidence: 0.942,
    referable: true,
    file_name: 'fundus_severe_npdr_03.jpg',
    patient: {
      patient_id: 'PAT-77312',
      name: 'Anil Deshmukh',
      age: 64,
      gender: 'Male' as const,
      examined_eye: 'OD - Right Eye' as const,
      diabetes_type: 'Type 2',
      duration_years: 18,
      clinician_notes: 'Patient reports progressive blurry vision in right eye over 3 months.',
    },
  },
  {
    id: 'sample-pdr',
    title: 'Preset: Proliferative DR (Grade 4)',
    description: 'Neovascularization at the disc (NVD), high risk of vitreous hemorrhage',
    stage: 4,
    stageName: 'Proliferative Diabetic Retinopathy',
    confidence: 0.967,
    referable: true,
    file_name: 'fundus_proliferative_dr_04.jpg',
    patient: {
      patient_id: 'PAT-90321',
      name: 'Sunita Rao',
      age: 69,
      gender: 'Female' as const,
      examined_eye: 'OS - Left Eye' as const,
      diabetes_type: 'Type 1',
      duration_years: 26,
      clinician_notes: 'Urgent referral required for panretinal photocoagulation (PRP).',
    },
  },
];

export const MOCK_PATIENTS: PatientInfo[] = [
  {
    patient_id: 'PAT-48291',
    name: 'Ramesh Patel',
    age: 58,
    gender: 'Male',
    examined_eye: 'OD - Right Eye',
    diabetes_type: 'Type 2',
    duration_years: 11,
    clinician_notes: 'Hypertension controlled. Last HbA1c: 8.2%. Complains of occasional floaters.',
  },
  {
    patient_id: 'PAT-10928',
    name: 'Priya Sharma',
    age: 42,
    gender: 'Female',
    examined_eye: 'OS - Left Eye',
    diabetes_type: 'Type 2',
    duration_years: 3,
    clinician_notes: 'Early detection protocol. Excellent glycemic control (HbA1c: 6.5%).',
  },
  {
    patient_id: 'PAT-77312',
    name: 'Anil Deshmukh',
    age: 64,
    gender: 'Male',
    examined_eye: 'OD - Right Eye',
    diabetes_type: 'Type 2',
    duration_years: 18,
    clinician_notes: 'Diabetic nephropathy co-morbidity. Requires urgent specialist review.',
  },
  {
    patient_id: 'PAT-90321',
    name: 'Sunita Rao',
    age: 69,
    gender: 'Female',
    examined_eye: 'OS - Left Eye',
    diabetes_type: 'Type 1',
    duration_years: 26,
    clinician_notes: 'History of macular edema in right eye. Left eye urgent screening.',
  },
  {
    patient_id: 'PAT-33821',
    name: 'Vikram Mehta',
    age: 51,
    gender: 'Male',
    examined_eye: 'OD - Right Eye',
    diabetes_type: 'Type 2',
    duration_years: 7,
    clinician_notes: 'Annual routine screening at mobile screening van.',
  },
  {
    patient_id: 'PAT-61902',
    name: 'Lakshmi Nair',
    age: 61,
    gender: 'Female',
    examined_eye: 'OS - Left Eye',
    diabetes_type: 'Type 2',
    duration_years: 14,
    clinician_notes: 'Laser therapy 2 years ago in contralateral eye.',
  },
];

export const MOCK_RECENT_SCREENINGS: ScreeningSession[] = [
  {
    id: 'SCR-9021',
    timestamp: '2026-08-30 08:42:15',
    patient: MOCK_PATIENTS[0],
    image_url: DEMO_FUNDUS_SVG,
    filename: 'fundus_od_48291.jpg',
    file_size_kb: 2450,
    dimensions: '2048 x 1536',
    prediction: {
      status: 'success',
      dr_grade: 2,
      severity_label: 'Moderate Non-Proliferative Diabetic Retinopathy',
      referable: true,
      confidence: 0.914,
      class_probabilities: {
        'Grade_0_No Diabetic Retinopathy': 0.012,
        'Grade_1_Mild Non-Proliferative Diabetic Retinopathy': 0.052,
        'Grade_2_Moderate Non-Proliferative Diabetic Retinopathy': 0.914,
        'Grade_3_Severe Non-Proliferative Diabetic Retinopathy': 0.018,
        'Grade_4_Proliferative Diabetic Retinopathy': 0.004,
      },
      gradcam_image: DEMO_HEATMAP_SVG,
      evidence: [
        'Multiple microaneurysms and localized blot intraretinal hemorrhages.',
        'Focal hard lipid exudates identified in macula or posterior pole.',
        'Mild cotton wool spots observed in temporal arcade.',
      ],
      quality_metric: {
        laplacian_variance: 168.4,
        is_blurry: false,
        threshold: 100.0,
        status: 'Pass',
      },
    },
    quality: {
      laplacian_variance: 168.4,
      is_blurry: false,
      threshold: 100.0,
      status: 'Pass',
    },
    review: {
      review_id: 'REV-101',
      status: 'verified',
      doctor_name: 'Dr. Arvind Sen, MD',
      doctor_id: 'DOC-8821',
      final_grade: 2,
      final_stage_name: 'Moderate Non-Proliferative Diabetic Retinopathy',
      notes: 'Confirmed moderate NPDR. Schedule OCT scan for macular edema evaluation.',
      reviewed_at: '2026-08-30 08:50:00',
    },
    report_id: 'NTR-9021A',
  },
  {
    id: 'SCR-9020',
    timestamp: '2026-08-30 08:15:30',
    patient: MOCK_PATIENTS[1],
    image_url: DEMO_FUNDUS_SVG,
    filename: 'fundus_os_10928.png',
    file_size_kb: 3120,
    dimensions: '2240 x 1680',
    prediction: {
      status: 'success',
      dr_grade: 0,
      severity_label: 'No Diabetic Retinopathy',
      referable: false,
      confidence: 0.985,
      class_probabilities: {
        'Grade_0_No Diabetic Retinopathy': 0.985,
        'Grade_1_Mild Non-Proliferative Diabetic Retinopathy': 0.011,
        'Grade_2_Moderate Non-Proliferative Diabetic Retinopathy': 0.002,
        'Grade_3_Severe Non-Proliferative Diabetic Retinopathy': 0.001,
        'Grade_4_Proliferative Diabetic Retinopathy': 0.001,
      },
      gradcam_image: DEMO_HEATMAP_SVG,
      evidence: [
        'Normal retinal background without microaneurysms or hemorrhages.',
        'Intact foveal avascular zone (FAZ) and sharp optic disc margins.',
      ],
      quality_metric: {
        laplacian_variance: 215.8,
        is_blurry: false,
        threshold: 100.0,
        status: 'Pass',
      },
    },
    quality: {
      laplacian_variance: 215.8,
      is_blurry: false,
      threshold: 100.0,
      status: 'Pass',
    },
    review: {
      review_id: 'REV-100',
      status: 'verified',
      doctor_name: 'Dr. Arvind Sen, MD',
      doctor_id: 'DOC-8821',
      final_grade: 0,
      final_stage_name: 'No Diabetic Retinopathy',
      notes: 'Clean baseline fundus photograph. Recall in 12 months for routine screening.',
      reviewed_at: '2026-08-30 08:22:10',
    },
    report_id: 'NTR-9020B',
  },
  {
    id: 'SCR-9019',
    timestamp: '2026-08-29 17:30:12',
    patient: MOCK_PATIENTS[2],
    image_url: DEMO_FUNDUS_SVG,
    filename: 'fundus_od_77312.jpg',
    file_size_kb: 1980,
    dimensions: '1920 x 1440',
    prediction: {
      status: 'success',
      dr_grade: 3,
      severity_label: 'Severe Non-Proliferative Diabetic Retinopathy',
      referable: true,
      confidence: 0.942,
      class_probabilities: {
        'Grade_0_No Diabetic Retinopathy': 0.002,
        'Grade_1_Mild Non-Proliferative Diabetic Retinopathy': 0.012,
        'Grade_2_Moderate Non-Proliferative Diabetic Retinopathy': 0.044,
        'Grade_3_Severe Non-Proliferative Diabetic Retinopathy': 0.942,
        'Grade_4_Proliferative Diabetic Retinopathy': 0.000,
      },
      gradcam_image: DEMO_HEATMAP_SVG,
      evidence: [
        'Severe intraretinal hemorrhages in all 4 quadrants.',
        'Definite Intraretinal Microvascular Abnormalities (IRMA).',
        'Prominent venous beading in inferior quadrant.',
      ],
      quality_metric: {
        laplacian_variance: 142.1,
        is_blurry: false,
        threshold: 100.0,
        status: 'Pass',
      },
    },
    quality: {
      laplacian_variance: 142.1,
      is_blurry: false,
      threshold: 100.0,
      status: 'Pass',
    },
    review: {
      review_id: 'REV-099',
      status: 'pending',
      doctor_name: 'Unassigned',
      doctor_id: '',
      final_grade: 3,
      final_stage_name: 'Severe Non-Proliferative Diabetic Retinopathy',
    },
  },
  {
    id: 'SCR-9018',
    timestamp: '2026-08-29 16:10:45',
    patient: MOCK_PATIENTS[3],
    image_url: DEMO_FUNDUS_SVG,
    filename: 'fundus_os_90321.jpg',
    file_size_kb: 2840,
    dimensions: '2100 x 1575',
    prediction: {
      status: 'success',
      dr_grade: 4,
      severity_label: 'Proliferative Diabetic Retinopathy',
      referable: true,
      confidence: 0.967,
      class_probabilities: {
        'Grade_0_No Diabetic Retinopathy': 0.001,
        'Grade_1_Mild Non-Proliferative Diabetic Retinopathy': 0.002,
        'Grade_2_Moderate Non-Proliferative Diabetic Retinopathy': 0.010,
        'Grade_3_Severe Non-Proliferative Diabetic Retinopathy': 0.020,
        'Grade_4_Proliferative Diabetic Retinopathy': 0.967,
      },
      gradcam_image: DEMO_HEATMAP_SVG,
      evidence: [
        'Active neovascularization of the optic disc (NVD).',
        'Preretinal fibrovascular proliferation observed.',
        'High acute risk of vision loss; immediate referral.',
      ],
      quality_metric: {
        laplacian_variance: 188.3,
        is_blurry: false,
        threshold: 100.0,
        status: 'Pass',
      },
    },
    quality: {
      laplacian_variance: 188.3,
      is_blurry: false,
      threshold: 100.0,
      status: 'Pass',
    },
    review: {
      review_id: 'REV-098',
      status: 'verified',
      doctor_name: 'Dr. Arvind Sen, MD',
      doctor_id: 'DOC-8821',
      final_grade: 4,
      final_stage_name: 'Proliferative Diabetic Retinopathy',
      notes: 'URGENT: Expedited tertiary referral booked for tomorrow morning for PRP.',
      reviewed_at: '2026-08-29 16:25:00',
    },
    report_id: 'NTR-9018C',
  },
  {
    id: 'SCR-9017',
    timestamp: '2026-08-29 14:05:22',
    patient: MOCK_PATIENTS[4],
    image_url: DEMO_FUNDUS_SVG,
    filename: 'fundus_od_33821.jpg',
    file_size_kb: 1750,
    dimensions: '1800 x 1350',
    prediction: {
      status: 'success',
      dr_grade: 1,
      severity_label: 'Mild Non-Proliferative Diabetic Retinopathy',
      referable: false,
      confidence: 0.882,
      class_probabilities: {
        'Grade_0_No Diabetic Retinopathy': 0.088,
        'Grade_1_Mild Non-Proliferative Diabetic Retinopathy': 0.882,
        'Grade_2_Moderate Non-Proliferative Diabetic Retinopathy': 0.024,
        'Grade_3_Severe Non-Proliferative Diabetic Retinopathy': 0.004,
        'Grade_4_Proliferative Diabetic Retinopathy': 0.002,
      },
      gradcam_image: DEMO_HEATMAP_SVG,
      evidence: [
        'Presence of isolated microaneurysms (< 5 detected).',
        'No hard exudates or diffuse intraretinal hemorrhages.',
      ],
      quality_metric: {
        laplacian_variance: 132.5,
        is_blurry: false,
        threshold: 100.0,
        status: 'Pass',
      },
    },
    quality: {
      laplacian_variance: 132.5,
      is_blurry: false,
      threshold: 100.0,
      status: 'Pass',
    },
    review: {
      review_id: 'REV-097',
      status: 'verified',
      doctor_name: 'Dr. Arvind Sen, MD',
      doctor_id: 'DOC-8821',
      final_grade: 1,
      final_stage_name: 'Mild Non-Proliferative Diabetic Retinopathy',
      notes: 'Advised strict glycemic and BP control. Follow-up screening in 6 months.',
      reviewed_at: '2026-08-29 14:20:00',
    },
    report_id: 'NTR-9017D',
  },
];

export const MOCK_REPORTS: ClinicalReport[] = [
  {
    report_id: 'NTR-9021A',
    patient: MOCK_PATIENTS[0],
    screening: MOCK_RECENT_SCREENINGS[0],
    analysis_result: MOCK_RECENT_SCREENINGS[0].prediction!,
    generated_at: '2026-08-30 08:52:10',
    status: 'reviewed',
    view_url: '/reports/NTR-9021A',
    download_url: '/reports/NTR-9021A?download=true',
  },
  {
    report_id: 'NTR-9020B',
    patient: MOCK_PATIENTS[1],
    screening: MOCK_RECENT_SCREENINGS[1],
    analysis_result: MOCK_RECENT_SCREENINGS[1].prediction!,
    generated_at: '2026-08-30 08:25:00',
    status: 'exported',
    view_url: '/reports/NTR-9020B',
    download_url: '/reports/NTR-9020B?download=true',
  },
  {
    report_id: 'NTR-9018C',
    patient: MOCK_PATIENTS[3],
    screening: MOCK_RECENT_SCREENINGS[3],
    analysis_result: MOCK_RECENT_SCREENINGS[3].prediction!,
    generated_at: '2026-08-29 16:30:15',
    status: 'reviewed',
    view_url: '/reports/NTR-9018C',
    download_url: '/reports/NTR-9018C?download=true',
  },
  {
    report_id: 'NTR-9017D',
    patient: MOCK_PATIENTS[4],
    screening: MOCK_RECENT_SCREENINGS[4],
    analysis_result: MOCK_RECENT_SCREENINGS[4].prediction!,
    generated_at: '2026-08-29 14:22:00',
    status: 'generated',
    view_url: '/reports/NTR-9017D',
    download_url: '/reports/NTR-9017D?download=true',
  },
];

export const MOCK_MODEL_METRICS: ModelMetrics = {
  model_name: 'MATLAB ResNet-18 (5-Class ICDR Staging)',
  task: '5-Class Diabetic Retinopathy ICDR Staging',
  device: 'MPS / Apple Silicon Neural Engine (or CUDA)',
  input_resolution: '224 x 224 px',
  accuracy: 0.894,
  sensitivity: 0.932,
  specificity: 0.887,
  precision: 0.891,
  f1_score: 0.908,
  qwk: 0.865,
  auc_roc: 0.961,
  is_demo: true,
  confusion_matrix: [
    [485, 12, 3, 0, 0],
    [15, 182, 18, 5, 0],
    [2, 21, 290, 22, 5],
    [0, 2, 19, 142, 17],
    [0, 0, 4, 11, 165],
  ],
  class_metrics: [
    { grade: 0, name: 'No DR', precision: 0.966, recall: 0.970, f1: 0.968, support: 500 },
    { grade: 1, name: 'Mild NPDR', precision: 0.839, recall: 0.827, f1: 0.833, support: 220 },
    { grade: 2, name: 'Moderate NPDR', precision: 0.868, recall: 0.853, f1: 0.860, support: 340 },
    { grade: 3, name: 'Severe NPDR', precision: 0.789, recall: 0.789, f1: 0.789, support: 180 },
    { grade: 4, name: 'Proliferative DR', precision: 0.882, recall: 0.917, f1: 0.899, support: 180 },
  ],
};

export const MOCK_SYSTEM_HEALTH: SystemHealthData = {
  status: 'operational',
  uptime_percentage: 99.98,
  average_latency_ms: 142,
  requests_today: 1842,
  error_rate: 0.002,
  components: [
    { name: 'FastAPI Backend Core', status: 'operational', latency: '28ms', description: 'RESTful API gateway & CORS middleware' },
    { name: 'MATLAB ResNet-18 Inference', status: 'ready', latency: '180ms', description: 'Deep learning feature extractor & ICDR head' },
    { name: 'Grad-CAM Explainability Engine', status: 'ready', latency: '220ms', description: 'Convolutional attention map generator (res5b_relu)' },
    { name: 'OpenCV Quality Gatekeeper', status: 'operational', latency: '18ms', description: 'Laplacian variance blur detector' },
    { name: 'Clinical Report Synthesizer', status: 'operational', latency: '45ms', description: 'Printable HTML & PDF rendering service' },
  ],
  recent_logs: [
    { id: 'LOG-8812', timestamp: '10:42:15', level: 'SUCCESS', endpoint: 'POST /analyze', message: 'Triage complete: Grade 2 (Moderate NPDR)', latency_ms: 382 },
    { id: 'LOG-8811', timestamp: '10:40:02', level: 'INFO', endpoint: 'GET /health', message: 'Health check OK: mode=live, device=mps', latency_ms: 12 },
    { id: 'LOG-8810', timestamp: '10:35:48', level: 'SUCCESS', endpoint: 'POST /report/generate', message: 'Generated report NTR-9021A', latency_ms: 48 },
    { id: 'LOG-8809', timestamp: '10:28:19', level: 'WARN', endpoint: 'POST /analyze', message: 'Quality gate rejected: Laplacian var 41.2 < 100', latency_ms: 64 },
    { id: 'LOG-8808', timestamp: '10:15:30', level: 'SUCCESS', endpoint: 'POST /analyze', message: 'Triage complete: Grade 0 (No DR)', latency_ms: 340 },
  ],
};
